### ISSUE TITLE
'Fore' is not defined

### ISSUE THREAD

**Issue by ImHasanx** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#15]
On Linux:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 333, in                                              
       _run_event
    await coro(*args, **kwargs)
  File "c-realV2.py", line 214, in on_ready
    print(f'| | {Fore.GREEN}Bot ready.')
NameError: name 'Fore' is not defined

**Comment by TKperson** [comment]
Do you have colorama installed on your python package?
I didn't include that package in the requirements.txt.
But you can use `pip3 install colorama` to fix it.

**Comment by ImHasanx** [comment]
Thx bro
