### ISSUE TITLE
Every time i type command in server it types this 

### ISSUE THREAD

**Issue by AmuSVK** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#25]
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "site-packages\discord\client.py", line 333, in _run_event
  File "c-realV2.py", line 318, in on_command_error
  File "c-realV2.py", line 276, in log
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by TKperson** [comment]
This is a well known bug for us right now.

But as for now you can don't really need the servers command to connect to a server. Use `connect <server id>` to connect.

**Comment by TKperson** [comment]
its now fixed
