### ISSUE TITLE
Error running any command

### ISSUE THREAD

**Issue by L3M0NFLUX** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#3]
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "c-real.py", line 171, in on_command_error
  File "lazyme\string.py", line 97, in color_print
TypeError: can only concatenate str (not "CheckFailure") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "discord\client.py", line 312, in _run_event
  File "c-real.py", line 173, in on_command_error
  File "discord\ext\commands\bot.py", line 903, in invoke
  File "discord\ext\commands\core.py", line 847, in invoke
  File "discord\ext\commands\core.py", line 777, in prepare
discord.ext.commands.errors.CheckFailure: The check functions for command kick failed.

Any command i do draws tons of errors! Please help!

**Comment by TKperson** [comment]
Can you state what command did you use?
And have you checked the permissions given to the bot?

**Comment by longphuc110** [comment]
All commands are unusable and have the same error as the user above.
please help!

**Comment by TKperson** [comment]
@longphuc110 I'll make the bot easier to use and add some error detection.
If you are getting many errors, then it's mostly because you did not configurate it right.
For the tutorial, I might going to make one.

**Comment by cyxl** [comment]
Closed
