### ISSUE TITLE
What version of discord.py do i use?

### ISSUE THREAD

**Issue by blank12344** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#33]
D:\Downloads\Nuking-Discord-Server-Bot-Nuke-Bot-master\Nuking-Discord-Server-Bot-Nuke-Bot-master>c-realV2.py
D:\Downloads\Nuking-Discord-Server-Bot-Nuke-Bot-master\Nuking-Discord-Server-Bot-Nuke-Bot-master\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.3) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "D:\Downloads\Nuking-Discord-Server-Bot-Nuke-Bot-master\Nuking-Discord-Server-Bot-Nuke-Bot-master\c-realV2.py", line 128, in <module>
    token, permissions, bomb_messages, webhook_spam, bot_permission, command_prefix, bot_status, verbose, after, proxies = readJson()
  File "D:\Downloads\Nuking-Discord-Server-Bot-Nuke-Bot-master\Nuking-Discord-Server-Bot-Nuke-Bot-master\c-realV2.py", line 83, in readJson
    temp = json.load(open(Path().absolute().__str__() + '/default.json'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 115: character maps to <undefined>

**Comment by TKperson** [comment]
I used python v3.8.5 32 bit to code this bot
I know that if you used any version below 3.8 will not work

**Comment by TKperson** [comment]
from this error I think you have some unicode characters contain in the default.json
after updating your python if it still shows you this error then you should consider remove the unicode you used.
And also if you can send me your default.json -- it would be pretty helpful for me to fix this unicode bug(if you used unicodes during configuration)

**Comment by blank12344** [comment]
i also get this when i run the .py directly 
![image](https://user-images.githubusercontent.com/80366996/110555771-076da800-80f2-11eb-84f3-d1f41dc8255f.png)

**Comment by TKperson** [comment]
it looks like you need to update your discord.py package as well.
use `pip install --upgrade discord.py `

**Comment by blank12344** [comment]
umm now im here 
![image](https://user-images.githubusercontent.com/80366996/110556179-d93c9800-80f2-11eb-86b1-4570e06e6789.png)

**Comment by blank12344** [comment]
[default - Copy.txt](https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/files/6112166/default.-.Copy.txt)

**Comment by TKperson** [comment]
oh it looks like you are in python virtual environment

You have to exit the python virtual environment
press control z or open up a new cmd

**Comment by blank12344** [comment]
so it is a unicode error 
![image](https://user-images.githubusercontent.com/80366996/110556567-a9da5b00-80f3-11eb-8912-9c3bf121ffa4.png)

**Comment by TKperson** [comment]
in your after command part you have `?kaboom 250 fixed` you should remove the command prefix to 'kaboom 250 fixed'

**Comment by TKperson** [comment]
yeah that was the unicode error i was talking about. You should use your user id instead of the name with unicode for the permission

Ill fix this in the next update

**Comment by TKperson** [comment]
you need to add your user id in there

**Comment by TKperson** [comment]
did you use the builder.html?

**Comment by blank12344** [comment]
yea
