### ISSUE TITLE
Why is This happening?

### ISSUE THREAD

**Issue by Poyebaneyyy** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#53]
What's the problem you are having while you are using C-REAL?

Have you checked the errors in the console?
Yes 
this is what I get :
Enter token. Note: Whatever you entered here will not be displayed.
>>

Enter your discord tag or user ID. It is recommended to use discord user ID because same unicode names are hard for the code to check.
>> 811297773****7507

Tips:
The default command_prefix is: .
Your currect command_prefix is: .
Use .config to config the settings and more info about how to config.

Traceback (most recent call last):
  File "C:\Users\%user%\Desktop\NUKIN\c-realV2.py", line 238, in <module>
    checkToken()
  File "C:\Users\%user%\Desktop\NUKIN\c-realV2.py", line 218, in checkToken
    if not 'id' in requests.get(url='https://discord.com/api/v8/users/@me', timeout=timeout, headers=headers).json():
  File "C:\Users\%user%\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Poyebaneyyy** [comment]
i can't run it with this error. bot is still offline

**Comment by TKperson** [comment]
I was able to recreate the error you had it looked like in cmd you can't copy and paste stuff. The programming environment that I was using didn't have the problem. I guess I'll remove the "hiding feature for now"

**Comment by Poyebaneyyy** [comment]
Thanks
