### ISSUE TITLE
Need help, what do I do?

### ISSUE THREAD

**Issue by rockdude129** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#66]
New C-REAL update has been launched -> 2.4.0 <- :party:
Ignoring exception in on_disconnect
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 249, in on_disconnect
    await changeStatus(None, 'offline')
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 374, in __call__
    return await self.callback(*args, **kwargs)
  File "main.py", line 1627, in changeStatus
    await client.change_presence(status=discord.Status.offline)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 1062, in change_presence
    await self.ws.change_presence(activity=activity, status=status, afk=afk)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/gateway.py", line 625, in change_presence
    await self.send(sent)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/gateway.py", line 587, in send
    await self.socket.send_str(data)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
PrivilegedIntentsRequired: This field is required to request for a list of members in the discord server that the bot is connected to. Watch https://youtu.be/DXnEFoHwL1A?t=44 to see how to turn on the required field.
Exiting...


**Comment by TKperson** [comment]
You didn't turn on the intents buttons, see: https://youtu.be/DXnEFoHwL1A?t=44

**Comment by rockdude129** [comment]
wow thank you!
