### ISSUE TITLE
ban isnt working

### ISSUE THREAD

**Issue by randomdude12122** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#7]
Unable to find <@780884389134336000>
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "c-real.py", line 328, in ban
AttributeError: 'NoneType' object has no attribute 'ban'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "discord\ext\commands\core.py", line 85, in wrapped
  File "c-real.py", line 331, in ban
AttributeError: 'NoneType' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\client.py", line 312, in _run_event
  File "c-real.py", line 173, in on_command_error
  File "discord\ext\commands\bot.py", line 903, in invoke
  File "discord\ext\commands\core.py", line 855, in invoke
  File "discord\ext\commands\core.py", line 94, in wrapped
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'name'

and when i ban all only i get banned nobody else does

**Comment by TKperson** [comment]
#10 has the same problem. V2 is out.
